name: Create GitHub Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --title "forecast-combo ${{ github.ref_name }}" --generate-notes --verify-tag
